version: "3.8"

services:
  app:
    build:
      context: .
      target: for-deploy
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: air
    environment:
      CHANNEL_SECRET: hoge
